apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot-api
  template:
    metadata:
      labels:
        app: chatbot-api
    spec:
      containers:
      - name: api
        image: yashraj777/chatbot-api:latest
        ports:
        - containerPort: 8000
        env:
        - name: MONGO_DB_NAME
          value: "MLAchatbot"
        - name: MONGO_STATE_CHECKPOINT_COLLECTION
          value: "checkpoints"
        - name: MONGO_STATE_WRITES_COLLECTION
          value: "checkpoints_writes_aio"
        - name: PINECONE_INDEX_NAME
          value: "demo-index"
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: chatbot-secrets
              key: OPENAI_API_KEY
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: chatbot-secrets
              key: MONGO_URI
        - name: PINECONE_API_KEY
          valueFrom:
            secretKeyRef:
              name: chatbot-secrets
              key: PINECONE_API_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: chatbot-api
spec:
  type: NodePort
  selector:
    app: chatbot-api
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30080
